services:
  - type: web
    name: task-buddy-app
    env: node
    plan: free

    rootDir: task-buddy-app-874
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist

    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: VITE_SUPABASE_PROJECT_ID
        sync: false
